# Generated by Django 3.1.4 on 2020-12-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerAccounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='aoount_type',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='account_type',
            field=models.CharField(choices=[('101', 'Saving'), ('102', 'Current'), ('103', 'DEMAT'), ('104', 'Fixed Deposit')], default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='account',
            name='accountNo',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
